import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${inter.className} container grid grid-col gap-16`}>
          <div className="container flex justify-evenly bg-gray-400">
            <Link href="/">Home</Link>
            <Link href="/create">Add</Link>
          </div>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
